### PR TITLE
add hide code option in example vignette

### PR DESCRIPTION
**Pull request by Chenhui-Jia**

### CODE REVIEW

**Comment by Chenhui-Jia** [comment]
@thuntran Hi Thu, since there are some long code chunks in the example vignette and they are unnecessary to show to the users, I added a button to let the users choose if they want to hide the code. But I am not sure about its effect on the website. Can you help me to check that? Thank you.

**Comment by thuntran** [comment]
Hi @Chenhui-Jia, I just checked it and if I'm not wrong I don't think the hide code option is reflected on the website

**Comment by thuntran** [comment]
Also for more convenient checking, I just created a website version based on your branch that you can access (actually everyone in the project) so you can check the changes by yourself too, if you're not aware of it (you can see it on readthedocs) https://repytah.readthedocs.io/en/chenhui/

**Comment by Chenhui-Jia** [comment]
Thank you! But since it does not show any weird displaying, I think I can keep that for the convenience of people who use jupyter notebook to open that file.

**Comment by thuntran** [comment]
Definitely! The build doesn't fail so I guess it won't hurt to keep the change

**Pull request merged**
