### PR TITLE
test solution to solve #322, add logo to readme

### PR DESCRIPTION
**Pull request by mariumtapal**

### CODE REVIEW

**Comment by mariumtapal** [comment]
Hello @Chenhui-Jia, @thuntran, @bwang64, @zoiezhao. Created a possible solution for the issue I opened last week. Could you test it in a separate conda environment to make sure this error is resolved? I would like to discuss this in today's meeting before merging though

**Comment by thuntran** [comment]
Not sure if I tested it correctly, but I did `pytest` in my default env which is `base` and another env that I just created. I got the same error for both envs:

ImportError while importing test module '/mnt/c/Users/Thu/desktop/surf2021/repytah/test/test_example.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/tntran/anaconda3/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/test_example.py:10: in <module>
    from repytah.input import *
E   ModuleNotFoundError: No module named 'repytah.input'

Let me know if I'm doing it correctly!

**Comment by mariumtapal** [comment]
> Not sure if I tested it correctly, but I did `pytest` in my default env which is `base` and another env that I just created. I got the same error for both envs:
> 
> ImportError while importing test module '/mnt/c/Users/Thu/desktop/surf2021/repytah/test/test_example.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> /home/tntran/anaconda3/lib/python3.8/importlib/**init**.py:127: in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> test/test_example.py:10: in 
> from repytah.input import *
> E ModuleNotFoundError: No module named 'repytah.input'
> 
> Let me know if I'm doing it correctly!

okay! Let me look into this again!

**Comment by mariumtapal** [comment]
@thuntran Hey Thu, could you re-pull the changes and test again? Also, before switching environments, did you build the package with `pip install -e .` or something similar?

**Comment by thuntran** [comment]
@mariumtapal Now that you mentioned it, I think I forgot to build the package in the new env... Yeah so to make sure I `pip install -e .` on both envs I tried and the tests worked perfectly now!

**Comment by bwang64** [comment]
I got the error like:FileNotFoundError: [Errno 2] No such file or directory: 'test/hierarchical_out_file.mat'
I ran the pip install instruction in the new env, not sure if that's right.

**Comment by mariumtapal** [comment]
> I got the error like:FileNotFoundError: [Errno 2] No such file or directory: 'test/hierarchical_out_file.mat'
> I ran the pip install instruction in the new env, not sure if that's right.

hey! are you sure you are testing on the marium branch, not main? because the file now exists in that branch

**Comment by bwang64** [comment]
> > I got the error like:FileNotFoundError: [Errno 2] No such file or directory: 'test/hierarchical_out_file.mat'
> > I ran the pip install instruction in the new env, not sure if that's right.
> 
> hey! are you sure you are testing on the marium branch, not main? because the file now exists in that branch

Oh! I see! I will try that again

**Comment by Chenhui-Jia** [comment]
I got two errors: NameError: name 'load_csv_input' is not defined; NameError: name 'get_y_labels' is not defined. But when I ran `pip install -e .`, I got a timeout error. Probably because I am on a train with unstable internet. Will try it again when I arrived at the hotel.

**Comment by bwang64** [comment]
> I got two errors: NameError: name 'load_csv_input' is not defined; NameError: name 'get_y_labels' is not defined. But when I ran `pip install -e .`, I got a timeout error. Probably because I am on a train with unstable internet. Will try it again when I arrived at the hotel.

Yes I got the same error:NameError: name 'load_csv_input' is not defined

**Comment by bwang64** [comment]
> I got two errors: NameError: name 'load_csv_input' is not defined; NameError: name 'get_y_labels' is not defined. But when I ran `pip install -e .`, I got a timeout error. Probably because I am on a train with unstable internet. Will try it again when I arrived at the hotel.

I also cannot run pip install -e ., but I can run python -m pip install -i https://test.pypi.org/simple/ repytah==0.1.0.dev0 --no-deps

**Comment by zoiezhao** [comment]
Hi! I test it on marium branch and get 4 nameError.

**Review by thuntran — APPROVED** [review]

**Review by bwang64 — APPROVED** [review]

**Comment by zoiezhao** [comment]
I pull again but i still get import error.

**Comment by bwang64** [comment]
> I pull again but i still get import error.

Did you run pip install -e .?

**Comment by mariumtapal** [comment]
> I pull again but i still get import error.

@zoiezhao hey! First pull the latest changes with `git pull`, then switch to the `marium` branch with `git checkout marium`.  Then install the updates in the package with `pip install -e .`. Then run `pytest -v`. If it still doesn't work, let me know!

**Pull request merged**
