### PR TITLE
updated example vignette according to Katie's suggestion no.2

### PR DESCRIPTION
**Pull request by Chenhui-Jia**
tie all_lst and complete_lst back to the thresholded SDM in the example vignette

### CODE REVIEW

**Review by zoiezhao — APPROVED** [review]
looks good to me! just the bolding of some words may be unnecessary but im not sure if that's your change, i can fix that later. Generally the tie back is good i think.

**Review by thuntran — APPROVED** [review]
Everything in general looks good to me, but I just see a little problem though I don't know if that matters: the colored text written right before the image of the function pipeline is not showing properly on github (I think we can only see bullet points and no text shown). Is there a way to make the colored text shown?

**Comment by Chenhui-Jia** [comment]
> looks good to me! just the bolding of some words may be unnecessary but im not sure if that's your change, i can fix that later. Generally the tie back is good i think.

I do not think I changed any bolding things, my computer probably messed it up. I will check that! Thank you.

**Comment by Chenhui-Jia** [comment]
> Everything in general looks good to me, but I just see a little problem though I don't know if that matters: the colored text written right before the image of the function pipeline is not showing properly on github (I think we can only see bullet points and no text shown). Is there a way to make the colored text shown?

I tried to show the module name after the bullet points in my new commit, but I don't have a way to solve the coloring problem yet.

**Comment by thuntran** [comment]
> > Everything in general looks good to me, but I just see a little problem though I don't know if that matters: the colored text written right before the image of the function pipeline is not showing properly on github (I think we can only see bullet points and no text shown). Is there a way to make the colored text shown?
> 
> I tried to show the module name after the bullet points in my new commit, but I don't have a way to solve the coloring problem yet.

So after some stackoverflow I suspect that GitHub doesn't support colored text (we can see it on the IDEs like Jupyter Notebook, VSCode and stuff but not on GitHub). Is it okay if we just remove the colors for that particular chunk of text? I think it will be nice to have, but since the purpose is to show the color, if the color annotation is not there and just the module names then I personally find it a bit awkward

**Comment by Chenhui-Jia** [comment]
> > > Everything in general looks good to me, but I just see a little problem though I don't know if that matters: the colored text written right before the image of the function pipeline is not showing properly on github (I think we can only see bullet points and no text shown). Is there a way to make the colored text shown?
> > 
> > 
> > I tried to show the module name after the bullet points in my new commit, but I don't have a way to solve the coloring problem yet.
> 
> So after some stackoverflow I suspect that GitHub doesn't support colored text (we can see it on the IDEs like Jupyter Notebook, VSCode and stuff but not on GitHub). Is it okay if we just remove the colors for that particular chunk of text? I think it will be nice to have, but since the purpose is to show the color, if the color annotation is not there and just the module names then I personally find it a bit awkward

Feeling the same. And another solution is to just remove the font tag.

**Comment by thuntran** [comment]
> > > > Everything in general looks good to me, but I just see a little problem though I don't know if that matters: the colored text written right before the image of the function pipeline is not showing properly on github (I think we can only see bullet points and no text shown). Is there a way to make the colored text shown?
> > > 
> > > 
> > > I tried to show the module name after the bullet points in my new commit, but I don't have a way to solve the coloring problem yet.
> > 
> > 
> > So after some stackoverflow I suspect that GitHub doesn't support colored text (we can see it on the IDEs like Jupyter Notebook, VSCode and stuff but not on GitHub). Is it okay if we just remove the colors for that particular chunk of text? I think it will be nice to have, but since the purpose is to show the color, if the color annotation is not there and just the module names then I personally find it a bit awkward
> 
> Feeling the same. And another solution is to just remove the font tag.

Yep that's actually what I mean! Just use normal black text I guess

**Comment by Chenhui-Jia** [comment]
> > > > > Everything in general looks good to me, but I just see a little problem though I don't know if that matters: the colored text written right before the image of the function pipeline is not showing properly on github (I think we can only see bullet points and no text shown). Is there a way to make the colored text shown?
> > > > 
> > > > 
> > > > I tried to show the module name after the bullet points in my new commit, but I don't have a way to solve the coloring problem yet.
> > > 
> > > 
> > > So after some stackoverflow I suspect that GitHub doesn't support colored text (we can see it on the IDEs like Jupyter Notebook, VSCode and stuff but not on GitHub). Is it okay if we just remove the colors for that particular chunk of text? I think it will be nice to have, but since the purpose is to show the color, if the color annotation is not there and just the module names then I personally find it a bit awkward
> > 
> > 
> > Feeling the same. And another solution is to just remove the font tag.
> 
> Yep that's actually what I mean! Just use normal black text I guess

Ok!! I will make the change. And will change all the vignettes.

**Comment by thuntran** [comment]
@Chenhui-Jia Oh, why do you close the PR? I think the other changes are fine!

**Comment by Chenhui-Jia** [comment]
> @Chenhui-Jia Oh, why do you close the PR? I think the other changes are fine!

oops, I accidentally closed it.

**Pull request merged**
